build:
  stage: build
  image: conanio/gcc72
  tags:
    - docker
  before_script:
     - sudo apt-get -qq update && sudo apt -qq -y install make git doxygen python3-pip
     - pip3 install 'Sphinx>=2.4.0,<3.0.0' sphinx-rtd-theme 'breathe<4.15.0' m2r 'mistune==0.8.4'
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DPARAMETRIC_BUILD_DOCS=ON -DCMAKE_INSTALL_PREFIX=../parametric-current ..
    - cmake --build .
    - cmake --build . --target Sphinx
    - cmake --build . --target install
  artifacts:
    expire_in: 2 hrs
    paths:
      - build/
      - parametric-current/

# run tests using the binary built before
test:
  stage: test
  image: ubuntu:18.04
  tags:
    - docker
  script:
    - cd build/tests
    - ./runUnitTests --gtest_output="xml:report.xml"
  artifacts:
    reports:
      junit: build/tests/report.xml

benchmark:
  stage: test
  image: ubuntu:18.04
  tags:
    - docker
  script:
    - cd build/benchmarks
    - ./benchmarks

docs:
  stage: deploy
  image: ubuntu:18.04
  tags:
    - docker
  dependencies:
    - build
  script:
    - mv build/docs/html parametric-docs
    - tar czf parametric-docs.tar.gz parametric-docs
  artifacts:
    paths:
      - parametric-docs.tar.gz
      
pages:
  stage: deploy
  image: ubuntu:18.04
  tags:
    - docker
  script:
    - mv build/docs/html public
  artifacts:
    paths:
      - public

package:
  stage: deploy
  image: ubuntu:18.04
  tags:
    - docker
  dependencies:
    - build
  script:
    - tar czf parametric-current.tar.gz parametric-current
  artifacts:
    paths:
      - parametric-current.tar.gz

conan:
  stage: deploy
  image: conanio/gcc72
  tags:
    - docker
  script:
    - conan remote add gitlab ${CI_API_V4_URL}/projects/21487/packages/conan
    - conan create . paradigms/testing
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload parametric/0.1@paradigms/testing --all --remote=gitlab

