[workspace]
name = "grunk"
version = "0.5.0"
authors = ["Jan Kleienrt <jan.kleinert@dlr.de>"]
platforms = ["win-64", "linux-64", "osx-64"]
channels = ["conda-forge"]

[dependencies]
cmake = "*"
ninja = "*"
doxygen = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
breathe = "*"
m2r = "*"
mistune = "*"
jinja2 = "<3.1"
standard-imghdr = "*"
docutils = "<0.21"

[tasks]
configure = { cmd = [
    "cmake", 
    "-G", "Ninja",
    "-S", ".",
    "-B", "build",
    "-D", "CMAKE_INSTALL_PREFIX=build/install",
    "-D", "CMAKE_BUILD_TYPE={{ config }}",
    "-D", "PARAMETRIC_BUILD_DOCS=ON"
], args = [
    { "arg" = "config", "default"="Release"},
]}
build = { cmd = "cmake --build . {{ extra_args }}", cwd = "build", args= [ { "arg" = "extra_args", "default" = "-j"}]}
install = { cmd = "cmake --build . --target install {{ extra_args }}", cwd = "build", args= [ { "arg" = "extra_args", "default" = "-j"}] }
test = { cmd = "./runUnitTests", cwd = "build/tests/" }