# SPDX-FileCopyrightText: 2026 Jan Kleinert <jan.kleinert@dlr.de>
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
name = "grunk"
version = "0.5.0"
authors = ["Jan Kleienrt <jan.kleinert@dlr.de>"]
platforms = ["win-64", "linux-64", "osx-64"]
channels = ["conda-forge"]

[feature.base.dependencies]
cmake = "*"
ninja = "*"

[feature.docs.dependencies]
doxygen = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
breathe = "*"
m2r = "*"
mistune = "*"
jinja2 = "<3.1"
standard-imghdr = "*"
docutils = "<0.21"

[feature.tools]
dependencies = { python = "*" }
pypi-dependencies = { reuse = "*", cffconvert = "*" }

[environments]
"default" = ["base"]
"docs" = ["base", "docs"]
"tools" = ["base", "tools"]

[tasks]
configure = { cmd = [
    "cmake", 
    "-G", "Ninja",
    "-S", ".",
    "-B", "build",
    "-D", "CMAKE_INSTALL_PREFIX=build/install",
    "-D", "CMAKE_BUILD_TYPE={{ config }}",
    "-D", "PARAMETRIC_BUILD_DOCS={{ docs }}",
    "-D", "PARAMETRIC_BUILD_TESTS=ON",
    "-D", "PARAMETRIC_BUILD_EXAMPLES=ON",
], args = [
    { "arg" = "config", "default"="Release"},
    { "arg" = "docs", "default"="ON"}
]}
build = { cmd = "cmake --build . {{ extra_args }}", cwd = "build", args= [ { "arg" = "extra_args", "default" = "-j"}]}
install = { cmd = "cmake --build . --target install {{ extra_args }}", cwd = "build", args= [ { "arg" = "extra_args", "default" = "-j"}] }
test = { cmd = "./runUnitTests", cwd = "build/tests/" }

#_reuse = { cmd = "reuse lint" }
_reuse = { cmd = "reuse {{ sub_cmd }}",args = [ { "arg" = "sub_cmd", "default" = "lint"} ] }

[tasks.reuse]
args = [ { "arg" = "sub_cmd", "default" = "lint"} ]
depends-on = [{ task = "_reuse", environment="tools", args = ["{{sub_cmd}}"] }]