name: CI

on:
  schedule:
    - cron: "20 3 * * 2"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - 'main'
    tags:
      - v*
  workflow_dispatch:

jobs:

  build-test:
    strategy:
      matrix:
        config: ["Release"]
        os: ["ubuntu-latest", "ubuntu-22.04", "windows-2022", "windows-latest", "macos-13"]
        include:
         - os: ubuntu-latest
           config: Debug
    uses: ./.github/workflows/build-test.yml
    secrets: inherit
    with:
      os: ${{ matrix.os }}
      config: ${{ matrix.config }}