name: CI

on:
  schedule:
    - cron: "20 3 * * 2"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - 'main'
    tags:
      - v*
  workflow_dispatch:

jobs:

  build-test:
    strategy:
      matrix:
        config: ["Release"]
        os: ["ubuntu-latest", "ubuntu-22.04", "windows-2022", "windows-latest", "macos-13"]
        build-docs: ["OFF"]
        include:
         - config: Release
           os: "ubuntu-latest"
           build-docs: "ON"
         - config: Debug
           os: ubuntu-latest
    uses: ./.github/workflows/build-test.yml
    secrets: inherit
    with:
      os: ${{ matrix.os }}
      config: ${{ matrix.config }}
      build-docs: ${{ matrix.build-docs }}
      env: ${{ matrix.build-docs == 'ON' && 'docs' || 'default'}}